sampleData <- read.csv("sampleSubmission.csv")
str(sampleData)
testData <- read.csv("test.csv",header = TRUE,sep =",")
str(testData)
trainData <- read.csv("train.csv",header=TRUE,sep=",")
str(trainData)
unique(trainData$Category)
nrow(trainData)
nrow(trainData['Category'=='ARSON'])
table(trainData$Category)
library(MASS)
categoryCount <- table(trainData$Category)
pie(categoryCount)
barplot(categoryCount)
barplot(categoryCount,main="Category",ylab = "Count",las=2,col=rainbow(nrow(categoryCount)))
library(ggmap)
downtown <- subset(trainData,min(trainData$X)<= trainData$X)
crimePoints <- subset(trainData,select=c(X,Y))
crimePoints = subset(trainData,Y!=90,select = c(X,Y,Category))
qmplot(X,Y,data=crimePoints[1:1000,],maptype = "toner-background")
qmplot(X,Y,data=crimePoints[1:10000,])
qmplot(X,Y,data=crimePoints,color=Category)
summary(trainData)
crimePerDayOfWeek <- table(trainData$DayOfWeek)
barplot(crimePerDayOfWeek,main="DayPerWeek",ylab = "Count",las=2,col=rainbow(nrow(crimePerDayOfWeek)))
trainData$dateOnly<-as.POSIXct(strptime(trainData$Dates,"%Y-%m-%d"))
library(ggplot2)
trainData$dateOnly<-format.Date(trainData$Dates,"%Y-%m-%d")
theme_set(theme_bw())
ggplot(as.data.frame(table(format.Date(trainData$Dates,"%Y"),dnn="Year")),aes(x=Year,y=Freq))+geom_point()+ggtitle("Per Year")
ggplot(as.data.frame(table(format.Date(trainData$Dates,"%m"),dnn="Month")),aes(x=Month,y=Freq))+geom_point()+ggtitle("Per Month")
ggplot(as.data.frame(table(format.Date(trainData$Dates,"%d"),dnn="Date")),aes(x=Date,y=Freq))+geom_point()+ggtitle("Per Date")
ggplot(as.data.frame(table(format.Date(trainData$Dates,"%Y-%m"),dnn="YearMonth")),aes(x=YearMonth,y=Freq))+geom_point()+ggtitle("Per Year Month")+theme(axis.text.x=element_text(angle=50,hjust=1,vjust=0.5))
ggplot(as.data.frame(table(format.Date(trainData$Dates,"%Y-%m-%d"),dnn="Date")),aes(x=Date,y=Freq))+geom_point()+ggtitle("Per Full Date")
